version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: okuuai_redis
    ports:
      - "${REDIS_PORT}:6379"  # Expose Ollama's service on port 6009
    command: ["redis-server", "--requirepass", "${REDIS_PWD}", "--loadmodule", "/opt/redis-stack/lib/redisearch.so"]  # Start Redis with a password
    volumes:
      - redis_data:/data  # Persist Redis data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: okuuai_ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "${OLLAMA_PORT}:11434"  # Expose Ollama's service on port 7009
    volumes:
      - ollama_data:/app/data
    restart: unless-stopped

volumes:
  redis_data:  # Persistent volume for Redis
  ollama_data:  # Persistent volume for Ollama
